#!/usr/bin/env bash

## Copyright (C) 2020-2025 Aditya Shakya <adi1090x@gmail.com>
##
## Welcome / Startup application for Archcraft

## Wayland
if [[ "$XDG_SESSION_TYPE" == 'wayland' ]]; then
    notify_cmd='notify-send'
else
    notify_cmd='dunstify'
fi

## Run Help
run_help() {
	if [[ -x `archcraft-help` ]]; then
		archcraft-help
	elif [[ -x `archcraft-help-prime` ]]; then
		archcraft-help-prime
	elif [[ -x `archcraft-help-wse` ]]; then
		archcraft-help-wse
	fi
}

DIR='/usr/share/archcraft/welcome'
stdbuf -oL -eL yad  --width='900' --height='570' --borders=0 --center \
					--title='Welcome' \
					--window-icon=archcraft-yellow \
					--no-buttons --no-escape \
                    --html --uri="$DIR/welcome.html" \
                    --print-uri 2>&1 \
| while read -r line; do
	case ${line##*/} in
		run_app1)  archcraft-help & ;;
		run_app2)  ${notify_cmd} -u low "Launching Calamares..." && /etc/calamares/launch.sh & ;;
		run_app3)  ${notify_cmd} -u low "Launching ABIF..." && alacritty --class 'alacritty-float,alacritty-float' --config-file /abif-master/alacritty.toml --title 'Archcraft Installer (CLI)' -e sudo /abif-master/abif & ;;
		*)		   echo "No URI" ;;
	esac
done
