#!/usr/bin/env bash

## Copyright (C) 2020-2021 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Welcome / Startup application for Archcraft

DIR='/usr/share/archcraft/welcome'
stdbuf -oL -eL yad  --width='900' --height='570' --borders=0 --center \
					--title='Welcome' \
					--window-icon=archcraft-yellow \
					--no-buttons --no-escape \
                    --html --uri="$DIR/welcome.html" \
                    --print-uri 2>&1 \
| while read -r line; do
	case ${line##*/} in
		run_app1)  help-and-tips & ;;
		run_app2)  dunstify -u low "Launching Calamares..." && /etc/calamares/launch.sh & ;;
		run_app3)  dunstify -u low "Launching ABIF..." && alacritty --config-file /abif-master/alacritty.yml --title 'Archcraft Installer (CLI)' -e sudo /abif-master/abif & ;;
		*)		   echo "No URI" ;;
	esac
done
