#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Help & Tips App for Archcraft

## Data
_dir='/usr/share/archcraft/help'
_file="$_dir/archcraft-help.pdf"

## Launch Main Window
zathura --mode=presentation "$_file"
