#!/usr/bin/env bash

## Copyright (C) 2020-2021 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Help & Tips App for Archcraft

## Data
_dir='/usr/share/archcraft/help'
_plug="$RANDOM"
_dialog_cmd="--html --disable-search --browser --print-uri --uri-handler='firefox --new-tab %s'"
_uri1="file://${_dir}/hello.html"
_uri2="file://${_dir}/about.html"
_uri3="file://${_dir}/openbox.html"
_uri4="file://${_dir}/bspwm.html"
_uri5="file://${_dir}/tips.html"
_uri6="file://${_dir}/community.html"

## Welcome Dialog
yad --plug="$_plug" --tabnum=1 ${_dialog_cmd} \
	--uri="${_uri1}" &> /tmp/res1 &

## About Dialog
yad --plug="$_plug" --tabnum=2 ${_dialog_cmd} \
	--uri="${_uri2}" &> /tmp/res2 &

## Openbox Dialog
yad --plug="$_plug" --tabnum=3 ${_dialog_cmd} \
	--uri="${_uri3}" &> /tmp/res3 &

## Bspwm Dialog
yad --plug="$_plug" --tabnum=4 ${_dialog_cmd} \
	--uri="${_uri4}" &> /tmp/res4 &

## Tips Dialog
yad --plug="$_plug" --tabnum=5 ${_dialog_cmd} \
	--uri="${_uri5}" &> /tmp/res5 &

## Donate Dialog
yad --plug="$_plug" --tabnum=6 ${_dialog_cmd} \
	--uri="${_uri6}" &> /tmp/res6 &

## Launch Main Window
yad --width='1150' --height='695' --borders=0 --center \
	--title='Help and Tips' \
	--window-icon=archcraft-purple \
	--no-buttons --no-escape \
	--notebook --key="$_plug" \
	--tab="Hello" --tab="About" --tab="Openbox" --tab="Bspwm" \
	--tab="Tips" --tab="Communities" \
	--tab-pos=top --tab-borders=0 --active-tab=1 \
	--expand --stack
